package oduoke.mapper;

public class TestTable extends AbsMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.id
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.content
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.id
     *
     * @return the value of test_table.id
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.id
     *
     * @param id the value for test_table.id
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.content
     *
     * @return the value of test_table.content
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.content
     *
     * @param content the value for test_table.content
     *
     * @mbggenerated Fri Sep 06 17:24:18 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}